#!/usr/bin/env bash
# Ensure Nginx listens on port 80

sudo systemctl start nginx
sleep 1
sudo sed -i '/listen 80 default_server;/s/# *//' /etc/nginx/sites-available/default
sudo systemctl restart nginx
sleep 1
sudo netstat -tuln | grep ":80 " >/dev/null || echo "Nginx is not running"
